name: Build, Package, Release (moodle-deployment.yaml)
description: Build and release a Docker image for AMD64 architecture without semantic release.
'on':
  release:
    types:
      - created
  push:
    branches:
      - main
env:
  VERSION: latest
  MO_DOCKERFILE: Dockerfile
  MO_DOCKERCONTEXT: .
  MO_REGISTRY_AUTH_URL: lmsdevcr.azurecr.io
  MO_REGISTRY_URL: lmsdevcr.azurecr.io/customlms
  MO_IMAGE_NAME: moodle
  MO_API_KIND: workspace
  MO_API_TOKEN_EXPIRES_AT__309A084A1207AB26556C: '2026-01-15T08:52:37.000Z'
  MO_SERVICE__309A084A1207AB26556C: H4sIAAAAAAAAA02Ou27DMBAE/2VrHaw3I9Zp0qR0fyJPBiGJJEjJQWL43wMpgJF2gNnZB0K6sXc/vLngPyw0hqqvTF2PpIzpqC2V0FDzREqNaiyn8q3rDAqYZc+bpFPpS1V1TTNQz7al1rQTsTUDjfUktWqbqjcVCnyFNOfIRj55FWgsayYrdxRIksOejEA/MDt/bL5LXML3Kn5DgbjsiRdo2BfNKMDRXSVlFzw0OMZ8uR8dz6ucHQu9pV2ef+il0xHeAq3hJt7t+b8CjRhmd/56/gI4QL4NHgEAAA==
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get last commit hash
        id: lastHash
        run: |
          LAST_HASH=$(git rev-parse --short HEAD)
          echo "LAST_HASH=$LAST_HASH" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.MO_REGISTRY_AUTH_URL }}
          username: ${{ secrets.MO_REGISTRY_USER__MOODLE_DEPLOYMENT }}
          password: ${{ secrets.MO_REGISTRY_PAT__MOODLE_DEPLOYMENT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push amd64 image
        id: buildAndPushImage
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.MO_DOCKERCONTEXT }}
          file: ${{ env.MO_DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:latest
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.LAST_HASH }}
          build-args: VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-309A084A1207AB26556C
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: false
          image: ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.LAST_HASH }}
          kind: Deployment
          namespace: poki-dev
          resourceName: deploy-lms-to-mogenius
          containerName: deploy-lms-to-mogenius
          keyKind: ${{ env.MO_API_KIND }}
          token: bearer ${{ secrets.MO_API_TOKEN__309A084A1207AB26556C__MOODLE_DEPLOYMENT }}
